typography_spectrum: 0.2486573
color:
  saturation: 0.09521071356721222
  brandStrength: 0.4688507
  lightness: 0.2624599891714752
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
  rhythmicContrast: 0.5207323839422315
layout_spectrum: 0.8105426412075758
name: Maria Coronel
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Seguros
description: Além do que se vê...
