typography_spectrum: 0.03484741039574146
color:
  saturation: 0.18597297370433807
  brandStrength: 0.3214159708004445
  lightness: 0.05232097930274904
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
  rhythmicContrast: 0.8526857988908887
layout_spectrum: 0.8420417963061482
name: Maria Coronel
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Seguros
description: Além do que se vê...
